.\"
.\" Man page for dcraw
.\"
.\" Copyright (c) 2012 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "3 maart 2015"
.LO 1
.SH NAAM
dcraw - command-line decoder voor RAW-afbeeldingen.
.SH SAMENVATTING
.B dcraw
[\fIOPTIE\fR]... [\fIBESTAND\fR]...
.SH BESCHRIJVING
.B dcraw
decodeert RAW-afbeeldingen, toont metagegevens en extraheert miniaturen.
.SH ALGEMENE OPTIES
.TP
.B -v
Alle meldingen afdrukken, niet alleen fouten en waarschuwingen.
.TP
.B -c
Schrijf gedecodeerde beelden of miniaturen naar de standaarduitvoer.
.TP
.B -e
Extraheer het ingebedde miniatuur, niet de RAW-afbeelding.
Afhankelijk van de camera levert dit een JPEG of PPM plaatje op.
.TP
.B -z
Wijzig toegangs- en bewerkingstijdstip van een AVI, JPEG, TIFF of
RAW-bestand naar tijdstip van opname, aangenomen dat de klok  van de
camera ingesteld is op de gecoördineerde wereldtijd (UTC).
.TP
.B -i
Toon korte omschrijving van bestanden, zonder ze te decoderen.
Stopstatus van het programma is 0 als
.B dcraw
het laatste beeld kan decoderen en 1 als dat niet zo is.
.B -i -v
Toon uitgebreidere omschrijving.
.TP
.B ""
.B dcraw
kan JPEG bestanden niet decoderen!!
.SH REPARATIE OPTIES
.TP
.B -I
Lees ruwe pixels uit de standaardinvoer in de bytevolgorde van de
computer en zonder header. Gebruik
.B dcraw -E -4
om de ruwe waarden op te slaan.
.TP
.B -P dode_pixels.txt
Lees de lijst met dode pixels uit dit bestand i.p.v. ".badpixels".
Zie ook
.B BESTANDEN
voor een beschrijving van het formaat.
.TP
.B -K donkerbeeld.pgm
Trek een donkerbeeld af van de ruwe gegevens. Om zo'n beeld te maken
schiet u een plaatje zonder dat er licht door de lens valt, vervolgens
ontwikkelt u het beeld zo:
.BR dcraw\ -D\ -4\ -j\ -t\ 0 .
.TP
.B -k zwart
Als schaduwen een grauwsluier hebben, dan moet u het zwartniveau
verhogen. Voor het juiste niveau past u
.B pamsumm -mean
toe op het donkerbeeld.
.TP
.B -S wit
Als hoge lichten roze zijn, dan moet u het witniveau verlagen.
Neem een foto van iets glimmends en doe:
.B dcraw -D -4 -j -c
foto.raw
.B | pamsumm -max
.TP
.B ""
De standaard zwart- en witniveaus zijn normaal gesproken juist.
.TP
.B -n ruisgrenswaarde
Gebruik wavelets om ruis te verwijderen en details te behouden.
De optimale grenswaarde licht meestal ergens tussen 100 en 1000.
.TP
.B -C rode_factor blauwe_factor
Schaal het rode en blauwe kanaal om de chromatische aberratie te
corrigeren, de optimale factoren liggen veelal tussen 0.999 en 1.001.
.TP
.B -H 0
Knip alle kleurkanalen op hetzelfde niveau af voor witte hoge lichten.
(standaard).
.TP
.B -H 1
Laat de hoge lichten ongemoeid in verschillende tinten roze.
.TP
.B -H 2
Meng overstuurde en niet overstuurde kleurkanalen voor een geleidelijk
verloop naar wit.
.TP
.B -H 3+
Repareer hoge lichten. Een lage waarde geeft wittere hoge lichten,
Een hoge kleurrijkere. Probeer
.B -H 5
als compromis.  Als dat niet goed genoeg is probeer dan
.BR -H\ 9 ,
knip de niet witte hoge lichten uit en plak ze in een plaatje dat
verkregen is met
.BR -H\ 3 .
.SH KLEUR OPTIES
Normaal gebruikt
.B dcraw
een witbalans die gebaseerd is op een kleurenkaart verlicht met een
standaard D65 lamp.
.TP
.B -w
Gebruik de witbalans van de camera, als deze niet gevonden wordt, druk
dan een waarschuwing af en gebruik een andere methode.
.TP
.B -a
Bereken de witbalans door het gehele beeld te middelen.
.TP
.B -A links rechts breedte hoogte
Bereken de witbalans door een rechthoekig gebied te middelen. Doe eerst
.B dcraw\ -j\ -t\ 0
en kies een neutraal grijs gebied.
.TP
.B -r mul0 mul1 mul2 mul3
Gebruik een handmatige witbalans.
De vermenigvuldigingsfactoren kunt u kopiëren uit de uitvoer van
.BR dcraw\ -v .
.TP
.BR +M " or " -M
Gebruik wel/geen kleurenmatrix uit de metagegevens van de camera.
De standaard is
.B +M
voor DNG-bestanden of als optie
.B -w
gebruikt wordt en
.B -M
als dat niet het geval is. Deze optie heeft naast DNG-bestanden
alleen betrekking op Olympus, Leaf, en Phase One camera's.
.TP
.B -o [0-5]
Kies de kleurruimte voor de uitvoer als de
.B -p
optie niet gebruikt wordt:

.B \t0
\ \ ruwe kleuren (afhankelijk van de camera)
.br
.B \t1
\ \ sRGB D65 (standaard)
.br
.B \t2
\ \ Adobe RGB (1998) D65
.br
.B \t3
\ \ Wide Gamut RGB D65
.br
.B \t4
\ \ Kodak ProPhoto RGB D65
.br
.B \t5
\ \ XYZ
.TP
.BR -p\ camera.icm \ [\  -o\ uitvoer.icm \ ]
Gebruik ICC profielen om de kleurruimtes van camera en uitvoer te
definiëren (standaard sRGB).
.TP
.B -p embed
Gebruik het ICC profiel ingebed in het RAW-bestand.
.SH INTERPOLATIE OPTIES
.TP
.B -d
Toon de RAW-afbeelding zonder interpolatie, als grijswaarden.
Goed voor gefotografeerde zwart-wit documenten.
.TP
.B -D
Zelfde als
.BR -d ,
maar dan zonder de grijswaarden te schalen.
.TP
.B -E
Zelfde als
.BR -D ,
maar zonder het beeld bij te snijden, laat alle ruwe pixels zien.
.TP
.B -h
Kleurenafbeelding op halve grootte, tweemaal zo snel als
.BR -q\ 0 .
.TP
.B -q 0
Gebruik snelle maar kwalitatief slechte bilineaire interpolatie.
.TP
.B -q 1
Gebruik Variable Number of Gradients (VNG) interpolatie.
.TP
.B -q 2
Gebruik Patterned Pixel Grouping (PPG) interpolatie.
.TP
.B -q 3
Gebruik Adaptive Homogeneity-Directed (AHD) interpolatie.
.TP
.B -f
Interpoleer RGGB als vier kleuren. Gebruik dit als in de uitvoer van
VNG of AHD visnet- respectievelijk doolhofpatronen te zien zijn.
.TP
.B -m aantal_filter_rondes
Ruim na interpolatie kleurartefacten op door herhaaldelijk een 3x3
mediaanfilter toe te passen op de R-G en B-G kanalen.
.SH UITVOER OPTIES
Normaal schrijft
.B dcraw
8-bits PGM/PPM/PAM bestanden naar de uitvoer, zonder metagegevens.
Deze foto's hebben een BT.709 gamma curve en een witniveau gebaseerd
op het beeldhistogram.
.TP
.B -W
Pas witniveau niet automatisch aan,
laat het beeldhistogram links liggen.
.TP
.B -b helderheid
Deel het witniveau door dit getal, standaard 1.0.
.TP
.B -g exponent voet
Stel de gamma curve in, standaard BT.709
.RB ( -g\ 2.222\ 4.5 ).
Als u liever de sRGB curve gebruikt:
.BR -g\ 2.4\ 12.92 .
Zet de voet op nul voor een simpele exponentiële curve.
.TP
.B -6
Schrijf 16-bits i.p.v. 8-bits gegevens.
.TP
.B -4
Lineair 16-bits, zelfde als
.BR -6\ -W\ -g\ 1\ 1 .
.TP
.B -T
Creëer een TIFF bestand met metagegevens i.p.v. een
PGM, PPM of PAM bestand.
.TP
.B -t [0-7,90,180,270]
Draai het beeld. Normaal gebruikt
.B dcraw
de door de camera opgegeven waarde.
.B -t 0
schakelt het draaien uit.
.TP
.B -j
Toon een 45 graden gedraaid beeld voor Fuji\ Super\ CCD camera's,
of een niet opgerekt beeld voor camera's met niet-vierkante pixels.
Met deze optie komt iedere pixel in de uitvoer overeen met exact één
pixel uit de invoer.
.TP
.BR "-s [0..N-1]" " or " "-s all"
Wanneer een bestand N RAW-afbeeldingen bevat, selecteer dan één
bepaald beeld of alle. Fuji\ Super\ CCD\ SR camera's
bijvoorbeeld, produceren twee beelden, waarvan er één vier stops
onderbelicht is, om detaillering in de hoge lichten te brengen.
.SH BESTANDEN
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
Lijst van dode pixels in uw camera die door
.B dcraw
gerepareerd moeten worden. Iedere regel in het bestand geeft regel,
kolom en UNIX tijd van overlijden van een pixel. Bijvoorbeeld:
.sp 1
.nf
 962   91 1028350000  # gestorven tussen 1 en 4 augustus 2002
1285 1067 0           # datum van overlijden onbekend
.fi
.sp 1
Pixel reparatie vindt plaats vóór draaien en rekken, dus gebruik
.B dcraw -j -t 0
om de juiste coördinaten van dode pixels te vinden.
.SH "ZIE OOK"
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pamsumm (1),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH AUTEUR
Geschreven door David Coffin, dcoffin a cybercom o net
.SH VERTALING
Frank Markesteijn, markesteijn a users o sourceforge o net
