.\"
.\" Man page for dcraw
.\"
.\" Copyright (c) 2015 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.\" Japanese Version Copyright (c) 2015 KITAGAWA Masahiro
.\" Translated Sat Mar 28 14:03:25 JST 2015
.\"         by KITAGAWA Masahiro
.TH dcraw 1 2015年3月3日
.LO 1
.SH 名前
dcraw - Raw デジタル写真のためのコマンドライン デコーダー
.SH 書式
.B dcraw
[\fIオプション]... [\fIファイル]...
.SH 説明
.B dcraw
Raw 写真をデコードし、メタデータを表示し、サムネイルを抽出する。
.SH 一般的オプション
.TP
.B -v
警告やエラーだけでなく、詳細なメッセージを出力する。
.TP
.B -c
デコードされた画像またはサムネイルを標準出力に書き出す。
.TP
.B -e
Raw 画像ではなく、カメラが生成したサムネイルを抽出する。
カメラによって、JPEG か PPM ファイルのどちらかが得られる。
.TP
.B -z
AVI, JPEG, TIFF, raw ファイルのアクセス時刻および改変時刻を
写真が撮影された時刻に変更する。
ただしカメラの時計が世界時に設定されていると見なす。
.TP
.B -i
ファイルをデコードせずに情報を表示する。
終了ステータスは、
.B dcraw
が最後のファイルのデコードに成功したときは 0、失敗したときは 1 となる。
.B -i -v
メタデータを表示する。
.TP
.B ""
.B dcraw
は JPEG ファイルをデコードできない!!
.SH 修復オプション
.TP
.B -I
Raw ピクセルを標準入力から CPU のバイト オーダーに従ってヘッダ無しで読み込む。
Raw ピクセル値を得るには
.B dcraw -E -4
を用いる。
.TP
.B -P deadpixels.txt
デッド ピクセルのリストを、".badpixels" の代わりにこのファイルから読み込む。
フォーマットの詳細は
.B FILES
を参照すること。
.TP
.B -K darkframe.pgm
Raw データからダーク フレームを差し引く。
ダーク フレームを生成するには、光が入らない状態で raw 写真を撮影して
.B dcraw\ -D\ -4\ -j\ -t\ 0
を実行する。
.TP
.B -k ダークネス
シャドウ部がぼやける場合は、ダークネス レベルを上げる必要がある。
これを測定するには、前述の方法で生成したダーク フレームに
.B pamsumm -mean
を適用する。
.TP
.B -S 飽和レベル
ハイライト部がピンク色を帯びる場合は、飽和レベル (saturation level) を下げる必要がある。
これを測定するには、何か輝くものを撮影して
.B dcraw -D -4 -j -c
photo.raw
.B | pamsumm -max
を実行する。
.TP
.B ""
既定のダークネスと飽和レベルが通常は適正値である。
.TP
.B -n ノイズ閾値
ウェーブレットを用いてリアルなディテールを維持しつつノイズを除去する。
最適な閾値は 100 と 1000 の間にあるはずである。
.TP
.B -C 赤乗数 青乗数
赤および青のレイヤーに与えられた乗数 (通常は 0.999 から 1.001) 
を掛けることで色収差を補正する。
.TP
.B -H 0
ハイライトすべてを完全な白にする (既定)。
.TP
.B -H 1
ハイライトをクリップせず、ピンクの濃淡として残す。
.TP
.B -H 2
クリップされた値とクリップされていない値とを混合し、白へ向かうグラデーションにする。
.TP
.B -H 3+
ハイライトを再構築する。値が低いほど白を重視し、高いほど色を重視する。
妥協点としては
.B -H 5
を試すとよい。それで不十分な場合は
.BR -H\ 9
の結果から白以外のハイライトを切り抜き、
.BR -H\ 3
で生成した画像に貼り付ける。
.SH 色オプション
既定では、
.B dcraw
は標準 D65 光源で照明されたカラー チャートに基づく固定されたホワイト バランスを用いる。
.TP
.B -w
カメラで指定されたホワイト バランスを用いる。
それが見つからない場合、警告を表示して別の方法を用いる。
.TP
.B -a
画像全体の平均からホワイト バランスを計算する。
.TP
.B -A 左 上 幅 高さ
矩形領域の平均からホワイト バランスを計算する。
まず
.B dcraw\ -j\ -t\ 0
を行ったうえで中間調灰色の領域を選択する。
.TP
.B -r 乗数0 乗数1 乗数2 乗数3
独自の raw ホワイト バランスを指定する。
これらの乗数としては
.BR dcraw\ -v
の出力をカット アンド ペーストできる。
.TP
.BR +M " または " -M
カメラのメタデータに基づく色行列を用いる (または用いない) 。
既定では、
.B -w
が設定されているか写真が DNG 形式であれば
.B+M
となり、そうでなければ
.B -M
となる。DNG 以外の場合、
このオプションは Olympus, Leaf, Phase One のカメラでのみ有効である。
.TP
.B -o [0-5]
.B -p
オプションを用いない場合の出力色空間を選択する:

.B \t0
\ \ Raw カラー (カメラごとに独自)
.br
.B \t1
\ \ sRGB D65 (既定)
.br
.B \t2
\ \ Adobe RGB (1998) D65
.br
.B \t3
\ \ Wide Gamut RGB D65
.br
.B \t4
\ \ Kodak ProPhoto RGB D65
.br
.B \t5
\ \ XYZ
.TP
.BR -p\ camera.icm \ [\  -o\ output.icm \ ]
ICC プロファイルを用いることでカメラの raw 色空間と
希望する出力色空間 (既定では sRGB) とを指定できる。
.TP
.B -p embed
Raw 写真に埋め込まれた ICC プロファイルを用いる。
.SH 補完オプション
.TP
.B -d
Raw データを補完なしでグレースケール画像として表示する。
白黒の文書の撮影に適している。
.TP
.B -D
.B -d
と同様だが、スケールされていない本来のピクセル値を用いる。
.TP
.B -E
.B -D
と同様だが、マスクされたピクセルは切り抜かれない。
.TP
.B -h
寸法が半分のカラー画像を出力する。
.BR -q\ 0 .
の約 2 倍高速である。
.TP
.B -q 0
高速で低品質なバイリニア補完を用いる。
.TP
.B -q 1
Variable Number of Gradients (VNG) 補完を用いる。
.TP
.B -q 2
Patterned Pixel Grouping (PPG) 補完を用いる。
.TP
.B -q 3
Adaptive Homogeneity\-Directed (AHD) 補完を用いる。
.TP
.B -f
RGB を 4 色として補完する。
VNG 補完での 2x2 格子状の模様や AHD 補完での迷路状の模様が出力に現れる場合にこれを用いる。
.TP
.B -m パス数
補完の後、3x3 メディアン フィルターを
R-G と B-G チャンネルに繰り返し適用することで偽色を除去する。
.SH 出力オプション
既定では、
.B dcraw
は 8 ビット サンプル・BT.709 ガンマ曲線・ヒストグラムに基づく白レベル・無メタデータの
PGM/PPM/PAM を出力する。
.TP
.B -W
画像のヒストグラムを無視し、白レベルに固定値を用いる。
.TP
.B -b 明るさ
白レベルをこの数値で割り算する。既定では 1.0 である。
.TP
.B -g 指数 足部の傾き
ガンマ曲線を設定する。既定では BT.709
.RB ( -g\ 2.222\ 4.5 )
である。sRGB ガンマを設定したい場合は
.BR -g\ 2.4\ 12.92
を用いる。単純な指数曲線では、足部の傾きを 0 に設定する。
.TP
.B -6
8 ビットではなく、16 ビット毎サンプルで出力する。
.TP
.B -4
線形 16 ビットで、
.BR -6\ -W\ -g\ 1\ 1
と同等である。
.TP
.B -T
メタデータ付きの TIFF を PGM/PPM/PAM の代わりに出力する。
.TP
.B -t [0-7,90,180,270]
出力画像を回転させる。既定では、
.B dcraw
はカメラで指定された回転を適用する。
.B -t 0
ですべての回転が無効になる。
.TP
.B -j
Fuji\ Super\ CCD カメラで、45 度傾いた画像を表示する。
ピクセルが正方形でないカメラでは、アスペクト比を修正するための伸張を行わない。
どの場合でも、このオプションは各ピクセルがひとつの
raw ピクセルに対応することを保証する。
.TP
.BR "-s [0..N-1]" " または " "-s all"
ファイルが N 枚の raw 画像を含んでいる場合、1 枚を選ぶか "all" で全てを選んでデコードする。
例として、Fuji\ Super\ CCD\ SR カメラでは 4 段だけ露出アンダーの第 2 画像を生成することで
ハイライト部のディテールを表示する。
.SH ファイル
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
カメラのデッド ピクセルのリストであり、
.B dcraw
 はこのリストに記載されたピクセルの周辺を補完する。
各行にひとつのピクセルの列、行、デッド ピクセルになった UNIX 時刻を記す。例:
.sp 1
.nf
 962   91 1028350000  # 2002年8月1日と4日の間にデッド ピクセル化
1285 1067 0           # いつデッド ピクセルになったか不明
.fi
.sp 1
座標は伸張や回転を行う前の値であり、つまり
.B dcraw -j -t 0
を用いてデッド ピクセルの位置が特定できる。
.SH 関連項目
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pamsumm (1),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH 著者
Written by David Coffin, dcoffin a cybercom o net
.SH 翻訳者
北川 雅裕, arctica0316 a gmail o com
